<robot name="test_robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="baselen" value="0.5" />
    <xacro:property name="baserad" value="0.5" />
    <xacro:property name="wheellen" value="0.05" />
    <xacro:property name="wheelrad" value="0.1" />

    <!--色の定義-->
    <material name="grey">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 1 1"/>
    </material>
    <material name="black">
        <color rgba="0.2 0.2 0.2 1"/>
    </material>

    <!--baseの慣性-->
    <xacro:macro name="base_inertia">
        <inertial>
            <origin xyz="0 0 ${(baselen/2)+0.05}"/>
            <mass value="2"/>
            <inertia ixx="${1/4*2*baserad*baserad+1/12*2*baselen}" ixy="0.0" ixz="0.0" iyy="${1/4*2*baserad*baserad+1/12*2*baselen}" iyz="0.0" izz="${1/2*2*baserad*baserad}"/>
        </inertial>
    </xacro:macro>

    <!--bodyの作成-->
    <link name="base_footprint">
        <origin xyz="0 0 0"/>
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder length="${baselen}" radius="${baserad}"/>
            </geometry>
            <origin xyz ="0 0 ${(baselen/2)+0.05}"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${baselen}" radius="${baserad}"/>
            </geometry>
            <origin xyz ="0 0 ${(baselen/2)+0.05}"/>
        </collision>
        <xacro:base_inertia/>
    </link>
    <gazebo reference="base_link">
        <material>
            Gazebo/Orange
        </material>
    </gazebo>    

    <!--lidarの作成-->
    <link name='LiDAR'>
        <visual>
            <geometry>
                <cylinder length="0.05" radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0"/>
            <material name="blue"/>
        </visual>
    </link>

    <!--右の車輪-->
    <link name="right_wheel">
        <visual>
        <geometry>
            <cylinder length="${wheellen}" radius="${wheelrad}"/>
        </geometry>
        <origin rpy="1.57075 0 0" xyz="0 0 0"/>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheellen}" radius="${wheelrad}"/>
            </geometry>
            <origin rpy="1.57075 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <origin rpy="1.57075 0 0" xyz="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="${1/4*1*wheelrad*wheelrad+1/12*2*wheellen}" ixy="0.0" ixz="0.0" iyy="${1/4*1*wheelrad*wheelrad+1/12*2*wheellen}" iyz="0.0" izz="${1/2*1*wheelrad*wheelrad}"/>
        </inertial>
    </link>
    <gazebo reference="right_wheel">
        <material>
            Gazebo/Black
        </material>
    </gazebo>    

    <!--左の車輪-->
    <link name="left_wheel">
        <visual>
        <geometry>
            <cylinder length="${wheellen}" radius="${wheelrad}"/>
        </geometry>
        <origin rpy="1.57075 0 0" xyz="0 0 0"/>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheellen}" radius="${wheelrad}"/>
            </geometry>
            <origin rpy="1.57075 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <origin rpy="1.57075 0 0" xyz="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="${1/4*1*wheelrad*wheelrad+1/12*2*wheellen}" ixy="0.0" ixz="0.0" iyy="${1/4*1*wheelrad*wheelrad+1/12*2*wheellen}" iyz="0.0" izz="${1/2*2*wheelrad*wheelrad}"/>
        </inertial>
    </link>
    <gazebo reference="left_wheel">
        <material>
            Gazebo/Black
        </material>
    </gazebo>    

    <!--受動輪-->
    <link name="caster_wheel">
        <visual>
        <geometry>
            <sphere radius="0.05"/>
        </geometry>
        <origin  xyz="0 0 0"/>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0"/>            
        </collision>
        <inertial>
            <origin  xyz="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="${2/5*1*0.05*0.05}" ixy="0" ixz="0" iyy="${2/5*1*0.05*0.05}" iyz="0" izz="${2/5*1*0.05*0.05}"/>
        </inertial>
    </link>


    <gazebo reference="caster_wheel">
        <material>
            Gazebo/Red
        </material>
    </gazebo>    


    <!--###########ジョイントの作成##########-->
    <!--base_footprintとbase_link-->
    <joint name="base_link_to_base_footprint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>
    <!--LiDARとbase_link-->
    <joint name="base_link_to_LiDAR" type="fixed">
        <parent link="base_link"/>
        <child link="LiDAR"/>
        <origin xyz = "0 0 ${baselen+0.05+0.05/2}"/>
    <axis xyz = "0 0 1"/>
    </joint>

    <!--base_linkとright_wheel-->
    <joint name="base_link_to_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz = "0 ${-(baserad+wheellen/2)} ${wheelrad}"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <!--base_linkとleft_wheel-->
    <joint name="base_link_to_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz = "0 ${baserad+wheellen/2} ${wheelrad}"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <!--base_linkとcaster_wheel-->
    <joint name="base_link_to_caster_wheel" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz = "-0.25 0 0.05"/>
        <axis xyz = "0 1 0"/>
    </joint>


    <gazebo>
    <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>

        <!-- wheels -->
        <left_joint>base_link_to_left_wheel</left_joint>
        <right_joint>base_link_to_right_wheel</right_joint>

        <!-- kinematics -->
        <wheel_separation>1.05</wheel_separation>
        <wheel_diameter>0.1</wheel_diameter>

        <!-- limits -->
        <max_wheel_torque>20</max_wheel_torque>
        <max_wheel_acceleration>1.0</max_wheel_acceleration>

        <!-- output -->
        <publish_odom>True</publish_odom>
        <publish_odom_tf>True</publish_odom_tf>
        <publish_wheel_tf>false</publish_wheel_tf>
        <publish_tf>true</publish_tf>

        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_link</robot_base_frame>
    </plugin>
    </gazebo>



    <gazebo reference="LiDAR">
        <sensor name="lidar" type="ray">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <pose>0 0 0 0 0 0</pose>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1.0</resolution>
                        <min_angle>0.0</min_angle>
                        <max_angle>6.28</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.12</min>
                    <max>12.0</max>
                    <resolution>0.02</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>LiDAR</frame_name>
            </plugin>

        </sensor>
        

    </gazebo>


</robot>
